targets:
  normal:
    tag_id: 1
    score: 5
    hit_effect: remove_one_opponent_armor_plate
    positions:
      - {name: T01_NorthMiddle, owner: blue, xy: [0.18, 1.26], yaw: -0.7854}
      - {name: T02_NorthEast, owner: blue, xy: [1.26, 1.26], yaw: -2.3562}
      - {name: T03_WestAboveGate, owner: blue, xy: [-1.26, 0.24], yaw: 0.7854}
      - {name: T04_WestBelowGate, owner: yellow, xy: [-1.26, -0.24], yaw: -0.7854}
      - {name: T05_EastAboveGate, owner: blue, xy: [1.26, 0.24], yaw: 2.3562}
      - {name: T06_EastBelowGate, owner: yellow, xy: [1.26, -0.24], yaw: -2.3562}
      - {name: T07_SouthWest, owner: yellow, xy: [-1.26, -1.26], yaw: 0.7854}
      - {name: T08_SouthMiddle, owner: yellow, xy: [-0.18, -1.26], yaw: 2.3562}
  base:
    yellow: {tag_id: 2, owner: yellow, xy: [1.36, -1.36], yaw: 2.3562, face_yaw_deg: 135, plane_angle_to_walls_deg: 45, pitch_deg: 0}
    blue: {tag_id: 3, owner: blue, xy: [-1.36, 1.36], yaw: -0.7854, face_yaw_deg: -45, plane_angle_to_walls_deg: 45, pitch_deg: 0}
  armor:
    plates_per_base: 4
    removal_order: [1, 2, 3, 4]
