from __future__ import annotations

import math


from robocup_visionrl_gym_env import (
    BASE_SHOOT_IDEAL_DISTANCE,
    BASE_SHOOT_MIN_RANGE,
    ROBOT_LENGTH,
    ROBOT_PUSHABLE_CLEARANCE_RADIUS,
    ROBOT_RADIUS,
    ROBOT_WIDTH,
    SHOOTER_FORWARD_OFFSET,
    SHOOT_IDEAL_DISTANCE,
    SHOOT_MIN_RANGE,
    SHOOT_RANGE
)

AGENTS = ("yellow", "blue")
TACTICAL_ACTION_DIM = 6
TACTICAL_ACTION_LABELS = (
    "target_selector",
    "base_rush_gate",
    "block_interference_gate",
    "recovery_gate",
    "fire_gate",
    "risk_preference",
)
SENSOR_FUSION_FEATURE_LABELS = (
    "robot_contact",
    "fused_localization_confidence",
    "wheel_imu_consistency",
    "scan_clearance",
    "tof_front_left_clearance",
    "tof_front_right_clearance",
    "bumper_or_hard_contact",
    "camera_target_visible",
    "pushable_contact",
)
SENSOR_FUSION_FEATURE_DIM = len(SENSOR_FUSION_FEATURE_LABELS)
SELFPLAY_OBSERVATION_DIM = 46
RECOVERY_CONFIDENCE_THRESHOLD = 0.28
RECOVERY_COOLDOWN_S = 2.50
BASE_RUSH_ARMOR_GATE = 3
BASE_RUSH_EARLY_NORMAL_HITS = 1
BASE_RUSH_BALANCED_NORMAL_HITS = 2
BASE_RUSH_PREFERRED_NORMAL_HITS = 3
TACTICAL_STANDOFF_MIN = SHOOTER_FORWARD_OFFSET + 0.24
TACTICAL_STANDOFF_MAX = SHOOTER_FORWARD_OFFSET + SHOOT_RANGE - 0.02
IDEAL_SHOOT_DISTANCE = SHOOT_IDEAL_DISTANCE
BASE_IDEAL_CENTER_STANDOFF = SHOOTER_FORWARD_OFFSET + BASE_SHOOT_IDEAL_DISTANCE
IDEAL_CENTER_STANDOFF = SHOOTER_FORWARD_OFFSET + SHOOT_IDEAL_DISTANCE
MIN_SHOOT_DISTANCE = SHOOT_MIN_RANGE
FIRE_GOAL_READY_RADIUS = 0.12
FIRE_YAW_TOLERANCE_RAD = 0.095
NORMAL_FIRE_HOLD_RADIUS = 0.180
BASE_FIRE_HOLD_RADIUS = 0.040
FIRE_POSE_BLOCKED_STEP_LIMIT = 6
NORMAL_ATTACK_STALE_STEP_LIMIT = 110
BASE_ATTACK_STALE_STEP_LIMIT = 80
SHOT_CLOSE_DISTANCE = SHOOTER_FORWARD_OFFSET + 0.14
BASE_SHOT_CLOSE_DISTANCE = SHOOTER_FORWARD_OFFSET + BASE_SHOOT_MIN_RANGE + 0.02
NORMAL_AIM_MICRO_SCAN_RAD = 0.014
BASE_AIM_MICRO_SCAN_RAD = 0.012
BASE_AIM_SEEK_SCAN_RAD = 0.018
BASE_FIRE_REPLAN_NUDGE_M = 0.008
SHOT_TIME_COST_SCALE = 0.035
PUSH_INTENT_THRESHOLD = 0.48
PUSH_STEP_M = 0.060
PUSH_ROBOT_RECOIL_M = 0.014
PUSH_CLEARANCE_MARGIN = 0.025
# Match the IsaacLab rendered wheel/body footprint so strict replay catches the
# same red-box overlap that is visible in video.
ROBOT_PUSHABLE_VISUAL_HALF_EXTENTS = (ROBOT_LENGTH * 0.5 + 0.110, ROBOT_WIDTH * 0.5 + 0.087)
DRAW_TIMEOUT_PENALTY = 14.0
NORMAL_TARGET_CONTACT_RADIUS = 0.035
BASE_TARGET_CONTACT_RADIUS = 0.045
PUSHABLE_CONTACT_RADIUS_SCALE = ROBOT_PUSHABLE_CLEARANCE_RADIUS / ROBOT_RADIUS
TOF_SENSOR_RANGE_M = 0.72
TOF_SENSOR_LATERAL_OFFSET_M = 0.070
FUSION_CONFIDENCE_RECOVERY_GAIN = 0.030
FUSION_CONFIDENCE_DRIFT_LOSS = 0.004
FUSION_HARD_CONTACT_LOSS = 0.025
FUSION_JAMMED_PUSH_LOSS = 0.020
ACCEL_DRIFT_LINEAR_THRESHOLD = 1.05
ACCEL_DRIFT_ANGULAR_THRESHOLD = 4.20
ACCEL_DRIFT_LOSS_SCALE = 0.020
CAMERA_MEMORY_FOV_RAD = math.radians(78.0)
CAMERA_MEMORY_RANGE_M = 1.15
POST_HIT_RETREAT_S = 0.42
POST_HIT_RETREAT_SPEED = -0.18
